-- MySQL Script generated by MySQL Workbench
-- 07/27/16 16:07:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`roles` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`roles` (
  `idroles` INT NOT NULL,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`tipodoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`tipodoc` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`tipodoc` (
  `idtipodoc` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipodoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`login` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`login` (
  `idlogin` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`Persona` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`Persona` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `celular` INT NOT NULL,
  `email` INT NOT NULL,
  `contraseña` VARCHAR(145) NOT NULL,
  `roles_idroles` INT NOT NULL,
  `tipodoc_idtipodoc` INT NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_Persona_roles_idx` (`roles_idroles` ASC),
  INDEX `fk_Persona_tipodoc1_idx` (`tipodoc_idtipodoc` ASC),
  INDEX `fk_Persona_login1_idx` (`login_idlogin` ASC),
  CONSTRAINT `fk_Persona_roles`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `pizzeria`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_tipodoc1`
    FOREIGN KEY (`tipodoc_idtipodoc`)
    REFERENCES `pizzeria`.`tipodoc` (`idtipodoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_login1`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `pizzeria`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`factura` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`factura` (
  `n°factura` INT NOT NULL,
  `iva_productos` INT(45) NOT NULL,
  `subtotal_producto` INT(45) NOT NULL,
  `total_factura` INT(45) NOT NULL,
  `fecha_facturación` VARCHAR(90) NOT NULL,
  `Persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`n°factura`),
  INDEX `fk_factura_Persona1_idx` (`Persona_idpersona` ASC),
  CONSTRAINT `fk_factura_Persona1`
    FOREIGN KEY (`Persona_idpersona`)
    REFERENCES `pizzeria`.`Persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`ingredientes` (
  `idingredientes` INT NOT NULL,
  `nombre_ingrediente` VARCHAR(45) NOT NULL,
  `precio_ingrediente` INT NOT NULL,
  PRIMARY KEY (`idingredientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`detalle_ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`detalle_ingredientes` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`detalle_ingredientes` (
  `codigo_detalle_ingrediente` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `ingredientes_idingredientes` INT NOT NULL,
  PRIMARY KEY (`codigo_detalle_ingrediente`),
  INDEX `fk_detalle_ingredientes_ingredientes1_idx` (`ingredientes_idingredientes` ASC),
  CONSTRAINT `fk_detalle_ingredientes_ingredientes1`
    FOREIGN KEY (`ingredientes_idingredientes`)
    REFERENCES `pizzeria`.`ingredientes` (`idingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`productos` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`productos` (
  `codigo_productos` INT NOT NULL,
  `detalle_productos` VARCHAR(200) NOT NULL,
  `valor_productos` INT(145) NOT NULL,
  `detalle_ingredientes_codigo_detalle_ingrediente` INT NOT NULL,
  PRIMARY KEY (`codigo_productos`),
  INDEX `fk_productos_detalle_ingredientes1_idx` (`detalle_ingredientes_codigo_detalle_ingrediente` ASC),
  CONSTRAINT `fk_productos_detalle_ingredientes1`
    FOREIGN KEY (`detalle_ingredientes_codigo_detalle_ingrediente`)
    REFERENCES `pizzeria`.`detalle_ingredientes` (`codigo_detalle_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`detalle_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`detalle_factura` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`detalle_factura` (
  `iddetalle_factura` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `valor_producto` INT NOT NULL,
  `productos_codigo_productos` INT NOT NULL,
  `factura_n°factura` INT NOT NULL,
  PRIMARY KEY (`iddetalle_factura`),
  UNIQUE INDEX `cantidad_UNIQUE` (`cantidad` ASC),
  INDEX `fk_detalle_factura_productos1_idx` (`productos_codigo_productos` ASC),
  INDEX `fk_detalle_factura_factura1_idx` (`factura_n°factura` ASC),
  CONSTRAINT `fk_detalle_factura_productos1`
    FOREIGN KEY (`productos_codigo_productos`)
    REFERENCES `pizzeria`.`productos` (`codigo_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`factura_n°factura`)
    REFERENCES `pizzeria`.`factura` (`n°factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`ingredientes_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`ingredientes_proveedor` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`ingredientes_proveedor` (
  `idingredientes_proveedor` INT NOT NULL,
  `cod_ingre_prov` INT NOT NULL,
  `productos_codigo_productos` INT NOT NULL,
  `proveedor_codigo_proveedor` INT NOT NULL,
  `ingredientes_idingredientes` INT NOT NULL,
  PRIMARY KEY (`idingredientes_proveedor`),
  INDEX `fk_ingredientes_proveedor_productos1_idx` (`productos_codigo_productos` ASC),
  INDEX `fk_ingredientes_proveedor_proveedor1_idx` (`proveedor_codigo_proveedor` ASC),
  INDEX `fk_ingredientes_proveedor_ingredientes1_idx` (`ingredientes_idingredientes` ASC),
  CONSTRAINT `fk_ingredientes_proveedor_productos1`
    FOREIGN KEY (`productos_codigo_productos`)
    REFERENCES `pizzeria`.`productos` (`codigo_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_codigo_proveedor`)
    REFERENCES `pizzeria`.`detalle_ingredientes` (`codigo_detalle_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_proveedor_ingredientes1`
    FOREIGN KEY (`ingredientes_idingredientes`)
    REFERENCES `pizzeria`.`ingredientes` (`idingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
